name: skripsi_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1
  another_stepper: ^1.2.2
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  flutter_inappwebview: ^6.0.0
  flutter_markdown: ^0.7.3+1
  vector_math: ^2.1.4
  flutter_compass: ^0.8.0
  onesignal_flutter: ^5.2.3
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/svgs/
  - assets/htmls/
  - assets/htmls/images/
  fonts:
  - family: PlusJakartaSans
    fonts:
    - asset: assets/fonts/PlusJakartaSans_Variable.ttf
      weight: 500
    - asset: assets/fonts/PlusJakartaSans_Variable_Italic.ttf
      style: italic
