name: skripsi_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  supabase_flutter: ^2.5.11
  google_sign_in: ^6.2.1
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0+1
  another_stepper: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: PlusJakartaSans
    fonts:
    - asset: assets/fonts/PlusJakartaSans_Variable.ttf
      weight: 500
    - asset: assets/fonts/PlusJakartaSans_Variable_Italic.ttf
      style: italic
